# 1. Configure the AWS Provider (you've already done this)
provider "aws" {
  region = "us-east-2" # Or your preferred region
}


# This configures the local provider (no settings needed)
provider "local" {}

# 2. Generate a new 2048-bit RSA private key
resource "tls_private_key" "my_key" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

# 3. Creates a new key pair in AWS, using the public key we just generated
resource "aws_key_pair" "my_aws_key" {

  key_name   = "web-key" # This is the name AWS will see

  public_key = tls_private_key.my_key.public_key_openssh
}

# 4. Saves the private key (that matches the public key) to your local disk
resource "local_file" "my_private_key" {

  content         = tls_private_key.my_key.private_key_pem
  filename        = "web-key.pem" # This is the file it will create
  file_permission = "0600"
}

# --- Call the Web Server Module ---
module "web_server" {
  # Path to the module directory relative to this file
  source = "./modules/ec2-webserver"

  # --- Provide values for the module's input variables ---
  ami_id          = var.ami_id                        # Pass the value from the root variables.tf
  instance_type   = var.instance_type                 # Pass the value from the root variables.tf
  key_name        = aws_key_pair.my_aws_key.key_name  # Pass the name generated by the aws_key_pair resource
  private_key_pem = local_file.my_private_key.content # Pass the content of the generated private key file (sensitive)
  index_html_path = "${path.root}/index.html"         # Provide the path to the index.html file in the root directory
  server_name     = "portfolio-server"       # Optionally override the default name (defined in module variables.tf)
}